/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.15.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QGroupBox *groupBox_set;
    QFrame *frame_color;
    QFrame *frame_color_old;
    QPushButton *pushButton_color_2;
    QPushButton *pushButton_color_old;
    QPushButton *pushButton_ok;
    QFrame *frame_color_new;
    QPushButton *pushButton_color_new;
    QGroupBox *groupBox;
    QLabel *label;
    QLineEdit *lineEdit_n;
    QGroupBox *groupBox_nodeList_2;
    QLineEdit *lineEdit_x0;
    QLabel *label_x0_2;
    QLabel *label_y0;
    QLineEdit *lineEdit_y0;
    QLabel *label_x1_5;
    QLineEdit *lineEdit_y1;
    QLabel *label_x1_2;
    QLineEdit *lineEdit_x1;
    QLabel *label_x1_7;
    QLineEdit *lineEdit_y2;
    QLabel *label_x1_9;
    QLineEdit *lineEdit_x2;
    QLabel *label_x1_11;
    QLineEdit *lineEdit_y3;
    QLabel *label_x1_12;
    QLineEdit *lineEdit_x3;
    QLabel *label_x1_13;
    QLineEdit *lineEdit_y4;
    QLabel *label_x1_14;
    QLineEdit *lineEdit_x4;
    QLabel *label_x1_15;
    QLineEdit *lineEdit_y5;
    QLabel *label_x1_16;
    QLineEdit *lineEdit_x5;
    QLabel *label_x1_17;
    QLineEdit *lineEdit_y6;
    QLabel *label_x1_18;
    QLineEdit *lineEdit_x6;
    QLabel *label_x1_19;
    QLineEdit *lineEdit_y7;
    QLabel *label_x1_20;
    QLineEdit *lineEdit_x7;
    QGroupBox *groupBox_2;
    QLabel *label_4;
    QLineEdit *lineEdit_n_c;
    QGroupBox *groupBox_nodeList_5;
    QLineEdit *lineEdit_x0_c;
    QLabel *label_x0_5;
    QLabel *label_y0_4;
    QLineEdit *lineEdit_y0_c;
    QLabel *label_x1_44;
    QLineEdit *lineEdit_y1_c;
    QLabel *label_x1_45;
    QLineEdit *lineEdit_x1_c;
    QLabel *label_x1_46;
    QLineEdit *lineEdit_y2_c;
    QLabel *label_x1_47;
    QLineEdit *lineEdit_x2_c;
    QLabel *label_x1_48;
    QLineEdit *lineEdit_y3_c;
    QLabel *label_x1_49;
    QLineEdit *lineEdit_x3_c;
    QLabel *label_x1_50;
    QLineEdit *lineEdit_y4_c;
    QLabel *label_x1_51;
    QLineEdit *lineEdit_x4_c;
    QLabel *label_x1_52;
    QLineEdit *lineEdit_y5_c;
    QLabel *label_x1_53;
    QLineEdit *lineEdit_x5_c;
    QLabel *label_x1_54;
    QLineEdit *lineEdit_y6_c;
    QLabel *label_x1_55;
    QLineEdit *lineEdit_x6_c;
    QLabel *label_x1_56;
    QLineEdit *lineEdit_y7_c;
    QLabel *label_x1_57;
    QLineEdit *lineEdit_x7_c;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1343, 561);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        groupBox_set = new QGroupBox(centralwidget);
        groupBox_set->setObjectName(QString::fromUtf8("groupBox_set"));
        groupBox_set->setGeometry(QRect(610, 10, 731, 501));
        frame_color = new QFrame(groupBox_set);
        frame_color->setObjectName(QString::fromUtf8("frame_color"));
        frame_color->setGeometry(QRect(80, 30, 80, 30));
        QPalette palette;
        frame_color->setPalette(palette);
        frame_color->setAutoFillBackground(true);
        frame_color->setFrameShape(QFrame::Panel);
        frame_color->setFrameShadow(QFrame::Sunken);
        frame_color_old = new QFrame(frame_color);
        frame_color_old->setObjectName(QString::fromUtf8("frame_color_old"));
        frame_color_old->setGeometry(QRect(0, 0, 80, 30));
        QPalette palette1;
        QBrush brush(QColor(0, 0, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush);
        palette1.setBrush(QPalette::Active, QPalette::Link, brush);
        QBrush brush1(QColor(208, 208, 208, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        QBrush brush2(QColor(46, 47, 48, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush2);
        QBrush brush3(QColor(0, 122, 244, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Inactive, QPalette::Link, brush3);
        QBrush brush4(QColor(164, 166, 168, 96));
        brush4.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Link, brush3);
        frame_color_old->setPalette(palette1);
        frame_color_old->setAutoFillBackground(true);
        frame_color_old->setFrameShape(QFrame::Panel);
        frame_color_old->setFrameShadow(QFrame::Sunken);
        pushButton_color_2 = new QPushButton(frame_color);
        pushButton_color_2->setObjectName(QString::fromUtf8("pushButton_color_2"));
        pushButton_color_2->setGeometry(QRect(140, 0, 92, 29));
        pushButton_color_old = new QPushButton(groupBox_set);
        pushButton_color_old->setObjectName(QString::fromUtf8("pushButton_color_old"));
        pushButton_color_old->setGeometry(QRect(220, 30, 92, 29));
        pushButton_ok = new QPushButton(groupBox_set);
        pushButton_ok->setObjectName(QString::fromUtf8("pushButton_ok"));
        pushButton_ok->setGeometry(QRect(320, 450, 92, 29));
        frame_color_new = new QFrame(groupBox_set);
        frame_color_new->setObjectName(QString::fromUtf8("frame_color_new"));
        frame_color_new->setGeometry(QRect(450, 30, 80, 30));
        QPalette palette2;
        QBrush brush5(QColor(255, 0, 0, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush5);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette2.setBrush(QPalette::Active, QPalette::BrightText, brush5);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush5);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush5);
        palette2.setBrush(QPalette::Active, QPalette::Link, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        QBrush brush6(QColor(255, 51, 51, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::Link, brush3);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::BrightText, brush5);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush5);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush5);
        palette2.setBrush(QPalette::Disabled, QPalette::Link, brush3);
        frame_color_new->setPalette(palette2);
        frame_color_new->setAutoFillBackground(true);
        frame_color_new->setFrameShape(QFrame::Panel);
        frame_color_new->setFrameShadow(QFrame::Sunken);
        pushButton_color_new = new QPushButton(groupBox_set);
        pushButton_color_new->setObjectName(QString::fromUtf8("pushButton_color_new"));
        pushButton_color_new->setGeometry(QRect(580, 30, 92, 29));
        groupBox = new QGroupBox(groupBox_set);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(10, 80, 351, 351));
        label = new QLabel(groupBox);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(70, 30, 69, 20));
        lineEdit_n = new QLineEdit(groupBox);
        lineEdit_n->setObjectName(QString::fromUtf8("lineEdit_n"));
        lineEdit_n->setGeometry(QRect(190, 30, 80, 20));
        groupBox_nodeList_2 = new QGroupBox(groupBox);
        groupBox_nodeList_2->setObjectName(QString::fromUtf8("groupBox_nodeList_2"));
        groupBox_nodeList_2->setGeometry(QRect(10, 60, 331, 281));
        lineEdit_x0 = new QLineEdit(groupBox_nodeList_2);
        lineEdit_x0->setObjectName(QString::fromUtf8("lineEdit_x0"));
        lineEdit_x0->setGeometry(QRect(80, 30, 80, 20));
        label_x0_2 = new QLabel(groupBox_nodeList_2);
        label_x0_2->setObjectName(QString::fromUtf8("label_x0_2"));
        label_x0_2->setGeometry(QRect(20, 30, 50, 20));
        label_x0_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_y0 = new QLabel(groupBox_nodeList_2);
        label_y0->setObjectName(QString::fromUtf8("label_y0"));
        label_y0->setGeometry(QRect(180, 30, 50, 20));
        label_y0->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_y0 = new QLineEdit(groupBox_nodeList_2);
        lineEdit_y0->setObjectName(QString::fromUtf8("lineEdit_y0"));
        lineEdit_y0->setGeometry(QRect(240, 30, 80, 20));
        label_x1_5 = new QLabel(groupBox_nodeList_2);
        label_x1_5->setObjectName(QString::fromUtf8("label_x1_5"));
        label_x1_5->setGeometry(QRect(180, 60, 50, 20));
        label_x1_5->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_y1 = new QLineEdit(groupBox_nodeList_2);
        lineEdit_y1->setObjectName(QString::fromUtf8("lineEdit_y1"));
        lineEdit_y1->setGeometry(QRect(240, 60, 80, 20));
        label_x1_2 = new QLabel(groupBox_nodeList_2);
        label_x1_2->setObjectName(QString::fromUtf8("label_x1_2"));
        label_x1_2->setGeometry(QRect(20, 60, 50, 20));
        label_x1_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_x1 = new QLineEdit(groupBox_nodeList_2);
        lineEdit_x1->setObjectName(QString::fromUtf8("lineEdit_x1"));
        lineEdit_x1->setGeometry(QRect(80, 60, 80, 20));
        label_x1_7 = new QLabel(groupBox_nodeList_2);
        label_x1_7->setObjectName(QString::fromUtf8("label_x1_7"));
        label_x1_7->setGeometry(QRect(180, 90, 50, 20));
        label_x1_7->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_y2 = new QLineEdit(groupBox_nodeList_2);
        lineEdit_y2->setObjectName(QString::fromUtf8("lineEdit_y2"));
        lineEdit_y2->setGeometry(QRect(240, 90, 80, 20));
        label_x1_9 = new QLabel(groupBox_nodeList_2);
        label_x1_9->setObjectName(QString::fromUtf8("label_x1_9"));
        label_x1_9->setGeometry(QRect(20, 90, 50, 20));
        label_x1_9->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_x2 = new QLineEdit(groupBox_nodeList_2);
        lineEdit_x2->setObjectName(QString::fromUtf8("lineEdit_x2"));
        lineEdit_x2->setGeometry(QRect(80, 90, 80, 20));
        label_x1_11 = new QLabel(groupBox_nodeList_2);
        label_x1_11->setObjectName(QString::fromUtf8("label_x1_11"));
        label_x1_11->setGeometry(QRect(180, 120, 50, 20));
        label_x1_11->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_y3 = new QLineEdit(groupBox_nodeList_2);
        lineEdit_y3->setObjectName(QString::fromUtf8("lineEdit_y3"));
        lineEdit_y3->setGeometry(QRect(240, 120, 80, 20));
        label_x1_12 = new QLabel(groupBox_nodeList_2);
        label_x1_12->setObjectName(QString::fromUtf8("label_x1_12"));
        label_x1_12->setGeometry(QRect(20, 120, 50, 20));
        label_x1_12->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_x3 = new QLineEdit(groupBox_nodeList_2);
        lineEdit_x3->setObjectName(QString::fromUtf8("lineEdit_x3"));
        lineEdit_x3->setGeometry(QRect(80, 120, 80, 20));
        label_x1_13 = new QLabel(groupBox_nodeList_2);
        label_x1_13->setObjectName(QString::fromUtf8("label_x1_13"));
        label_x1_13->setGeometry(QRect(180, 150, 50, 20));
        label_x1_13->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_y4 = new QLineEdit(groupBox_nodeList_2);
        lineEdit_y4->setObjectName(QString::fromUtf8("lineEdit_y4"));
        lineEdit_y4->setGeometry(QRect(240, 150, 80, 20));
        label_x1_14 = new QLabel(groupBox_nodeList_2);
        label_x1_14->setObjectName(QString::fromUtf8("label_x1_14"));
        label_x1_14->setGeometry(QRect(20, 150, 50, 20));
        label_x1_14->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_x4 = new QLineEdit(groupBox_nodeList_2);
        lineEdit_x4->setObjectName(QString::fromUtf8("lineEdit_x4"));
        lineEdit_x4->setGeometry(QRect(80, 150, 80, 20));
        label_x1_15 = new QLabel(groupBox_nodeList_2);
        label_x1_15->setObjectName(QString::fromUtf8("label_x1_15"));
        label_x1_15->setGeometry(QRect(180, 180, 50, 20));
        label_x1_15->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_y5 = new QLineEdit(groupBox_nodeList_2);
        lineEdit_y5->setObjectName(QString::fromUtf8("lineEdit_y5"));
        lineEdit_y5->setGeometry(QRect(240, 180, 80, 20));
        label_x1_16 = new QLabel(groupBox_nodeList_2);
        label_x1_16->setObjectName(QString::fromUtf8("label_x1_16"));
        label_x1_16->setGeometry(QRect(20, 180, 50, 20));
        label_x1_16->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_x5 = new QLineEdit(groupBox_nodeList_2);
        lineEdit_x5->setObjectName(QString::fromUtf8("lineEdit_x5"));
        lineEdit_x5->setGeometry(QRect(80, 180, 80, 20));
        label_x1_17 = new QLabel(groupBox_nodeList_2);
        label_x1_17->setObjectName(QString::fromUtf8("label_x1_17"));
        label_x1_17->setGeometry(QRect(180, 210, 50, 20));
        label_x1_17->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_y6 = new QLineEdit(groupBox_nodeList_2);
        lineEdit_y6->setObjectName(QString::fromUtf8("lineEdit_y6"));
        lineEdit_y6->setGeometry(QRect(240, 210, 80, 20));
        label_x1_18 = new QLabel(groupBox_nodeList_2);
        label_x1_18->setObjectName(QString::fromUtf8("label_x1_18"));
        label_x1_18->setGeometry(QRect(20, 210, 50, 20));
        label_x1_18->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_x6 = new QLineEdit(groupBox_nodeList_2);
        lineEdit_x6->setObjectName(QString::fromUtf8("lineEdit_x6"));
        lineEdit_x6->setGeometry(QRect(80, 210, 80, 20));
        label_x1_19 = new QLabel(groupBox_nodeList_2);
        label_x1_19->setObjectName(QString::fromUtf8("label_x1_19"));
        label_x1_19->setGeometry(QRect(180, 240, 50, 20));
        label_x1_19->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_y7 = new QLineEdit(groupBox_nodeList_2);
        lineEdit_y7->setObjectName(QString::fromUtf8("lineEdit_y7"));
        lineEdit_y7->setGeometry(QRect(240, 240, 80, 20));
        label_x1_20 = new QLabel(groupBox_nodeList_2);
        label_x1_20->setObjectName(QString::fromUtf8("label_x1_20"));
        label_x1_20->setGeometry(QRect(20, 240, 50, 20));
        label_x1_20->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_x7 = new QLineEdit(groupBox_nodeList_2);
        lineEdit_x7->setObjectName(QString::fromUtf8("lineEdit_x7"));
        lineEdit_x7->setGeometry(QRect(80, 240, 80, 20));
        groupBox_2 = new QGroupBox(groupBox_set);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(370, 80, 351, 351));
        label_4 = new QLabel(groupBox_2);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(70, 30, 69, 20));
        lineEdit_n_c = new QLineEdit(groupBox_2);
        lineEdit_n_c->setObjectName(QString::fromUtf8("lineEdit_n_c"));
        lineEdit_n_c->setGeometry(QRect(190, 30, 80, 20));
        groupBox_nodeList_5 = new QGroupBox(groupBox_2);
        groupBox_nodeList_5->setObjectName(QString::fromUtf8("groupBox_nodeList_5"));
        groupBox_nodeList_5->setGeometry(QRect(10, 60, 331, 281));
        lineEdit_x0_c = new QLineEdit(groupBox_nodeList_5);
        lineEdit_x0_c->setObjectName(QString::fromUtf8("lineEdit_x0_c"));
        lineEdit_x0_c->setGeometry(QRect(80, 30, 80, 20));
        label_x0_5 = new QLabel(groupBox_nodeList_5);
        label_x0_5->setObjectName(QString::fromUtf8("label_x0_5"));
        label_x0_5->setGeometry(QRect(20, 30, 50, 20));
        label_x0_5->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_y0_4 = new QLabel(groupBox_nodeList_5);
        label_y0_4->setObjectName(QString::fromUtf8("label_y0_4"));
        label_y0_4->setGeometry(QRect(180, 30, 50, 20));
        label_y0_4->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_y0_c = new QLineEdit(groupBox_nodeList_5);
        lineEdit_y0_c->setObjectName(QString::fromUtf8("lineEdit_y0_c"));
        lineEdit_y0_c->setGeometry(QRect(240, 30, 80, 20));
        label_x1_44 = new QLabel(groupBox_nodeList_5);
        label_x1_44->setObjectName(QString::fromUtf8("label_x1_44"));
        label_x1_44->setGeometry(QRect(180, 60, 50, 20));
        label_x1_44->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_y1_c = new QLineEdit(groupBox_nodeList_5);
        lineEdit_y1_c->setObjectName(QString::fromUtf8("lineEdit_y1_c"));
        lineEdit_y1_c->setGeometry(QRect(240, 60, 80, 20));
        label_x1_45 = new QLabel(groupBox_nodeList_5);
        label_x1_45->setObjectName(QString::fromUtf8("label_x1_45"));
        label_x1_45->setGeometry(QRect(20, 60, 50, 20));
        label_x1_45->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_x1_c = new QLineEdit(groupBox_nodeList_5);
        lineEdit_x1_c->setObjectName(QString::fromUtf8("lineEdit_x1_c"));
        lineEdit_x1_c->setGeometry(QRect(80, 60, 80, 20));
        label_x1_46 = new QLabel(groupBox_nodeList_5);
        label_x1_46->setObjectName(QString::fromUtf8("label_x1_46"));
        label_x1_46->setGeometry(QRect(180, 90, 50, 20));
        label_x1_46->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_y2_c = new QLineEdit(groupBox_nodeList_5);
        lineEdit_y2_c->setObjectName(QString::fromUtf8("lineEdit_y2_c"));
        lineEdit_y2_c->setGeometry(QRect(240, 90, 80, 20));
        label_x1_47 = new QLabel(groupBox_nodeList_5);
        label_x1_47->setObjectName(QString::fromUtf8("label_x1_47"));
        label_x1_47->setGeometry(QRect(20, 90, 50, 20));
        label_x1_47->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_x2_c = new QLineEdit(groupBox_nodeList_5);
        lineEdit_x2_c->setObjectName(QString::fromUtf8("lineEdit_x2_c"));
        lineEdit_x2_c->setGeometry(QRect(80, 90, 80, 20));
        label_x1_48 = new QLabel(groupBox_nodeList_5);
        label_x1_48->setObjectName(QString::fromUtf8("label_x1_48"));
        label_x1_48->setGeometry(QRect(180, 120, 50, 20));
        label_x1_48->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_y3_c = new QLineEdit(groupBox_nodeList_5);
        lineEdit_y3_c->setObjectName(QString::fromUtf8("lineEdit_y3_c"));
        lineEdit_y3_c->setGeometry(QRect(240, 120, 80, 20));
        label_x1_49 = new QLabel(groupBox_nodeList_5);
        label_x1_49->setObjectName(QString::fromUtf8("label_x1_49"));
        label_x1_49->setGeometry(QRect(20, 120, 50, 20));
        label_x1_49->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_x3_c = new QLineEdit(groupBox_nodeList_5);
        lineEdit_x3_c->setObjectName(QString::fromUtf8("lineEdit_x3_c"));
        lineEdit_x3_c->setGeometry(QRect(80, 120, 80, 20));
        label_x1_50 = new QLabel(groupBox_nodeList_5);
        label_x1_50->setObjectName(QString::fromUtf8("label_x1_50"));
        label_x1_50->setGeometry(QRect(180, 150, 50, 20));
        label_x1_50->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_y4_c = new QLineEdit(groupBox_nodeList_5);
        lineEdit_y4_c->setObjectName(QString::fromUtf8("lineEdit_y4_c"));
        lineEdit_y4_c->setGeometry(QRect(240, 150, 80, 20));
        label_x1_51 = new QLabel(groupBox_nodeList_5);
        label_x1_51->setObjectName(QString::fromUtf8("label_x1_51"));
        label_x1_51->setGeometry(QRect(20, 150, 50, 20));
        label_x1_51->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_x4_c = new QLineEdit(groupBox_nodeList_5);
        lineEdit_x4_c->setObjectName(QString::fromUtf8("lineEdit_x4_c"));
        lineEdit_x4_c->setGeometry(QRect(80, 150, 80, 20));
        label_x1_52 = new QLabel(groupBox_nodeList_5);
        label_x1_52->setObjectName(QString::fromUtf8("label_x1_52"));
        label_x1_52->setGeometry(QRect(180, 180, 50, 20));
        label_x1_52->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_y5_c = new QLineEdit(groupBox_nodeList_5);
        lineEdit_y5_c->setObjectName(QString::fromUtf8("lineEdit_y5_c"));
        lineEdit_y5_c->setGeometry(QRect(240, 180, 80, 20));
        label_x1_53 = new QLabel(groupBox_nodeList_5);
        label_x1_53->setObjectName(QString::fromUtf8("label_x1_53"));
        label_x1_53->setGeometry(QRect(20, 180, 50, 20));
        label_x1_53->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_x5_c = new QLineEdit(groupBox_nodeList_5);
        lineEdit_x5_c->setObjectName(QString::fromUtf8("lineEdit_x5_c"));
        lineEdit_x5_c->setGeometry(QRect(80, 180, 80, 20));
        label_x1_54 = new QLabel(groupBox_nodeList_5);
        label_x1_54->setObjectName(QString::fromUtf8("label_x1_54"));
        label_x1_54->setGeometry(QRect(180, 210, 50, 20));
        label_x1_54->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_y6_c = new QLineEdit(groupBox_nodeList_5);
        lineEdit_y6_c->setObjectName(QString::fromUtf8("lineEdit_y6_c"));
        lineEdit_y6_c->setGeometry(QRect(240, 210, 80, 20));
        label_x1_55 = new QLabel(groupBox_nodeList_5);
        label_x1_55->setObjectName(QString::fromUtf8("label_x1_55"));
        label_x1_55->setGeometry(QRect(20, 210, 50, 20));
        label_x1_55->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_x6_c = new QLineEdit(groupBox_nodeList_5);
        lineEdit_x6_c->setObjectName(QString::fromUtf8("lineEdit_x6_c"));
        lineEdit_x6_c->setGeometry(QRect(80, 210, 80, 20));
        label_x1_56 = new QLabel(groupBox_nodeList_5);
        label_x1_56->setObjectName(QString::fromUtf8("label_x1_56"));
        label_x1_56->setGeometry(QRect(180, 240, 50, 20));
        label_x1_56->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_y7_c = new QLineEdit(groupBox_nodeList_5);
        lineEdit_y7_c->setObjectName(QString::fromUtf8("lineEdit_y7_c"));
        lineEdit_y7_c->setGeometry(QRect(240, 240, 80, 20));
        label_x1_57 = new QLabel(groupBox_nodeList_5);
        label_x1_57->setObjectName(QString::fromUtf8("label_x1_57"));
        label_x1_57->setGeometry(QRect(20, 240, 50, 20));
        label_x1_57->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_x7_c = new QLineEdit(groupBox_nodeList_5);
        lineEdit_x7_c->setObjectName(QString::fromUtf8("lineEdit_x7_c"));
        lineEdit_x7_c->setGeometry(QRect(80, 240, 80, 20));
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 1343, 25));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "\350\243\201\345\211\252\357\274\232W-A\345\244\232\350\276\271\345\275\242\350\243\201\345\211\252", nullptr));
        groupBox_set->setTitle(QCoreApplication::translate("MainWindow", "\345\217\202\346\225\260\350\256\276\347\275\256", nullptr));
        pushButton_color_2->setText(QCoreApplication::translate("MainWindow", "\346\233\264\346\224\271\351\242\234\350\211\262", nullptr));
        pushButton_color_old->setText(QCoreApplication::translate("MainWindow", "\350\243\201\345\211\252\345\211\215\351\242\234\350\211\262", nullptr));
        pushButton_ok->setText(QCoreApplication::translate("MainWindow", "\347\241\256\345\256\232", nullptr));
        pushButton_color_new->setText(QCoreApplication::translate("MainWindow", "\350\243\201\345\211\252\345\220\216\351\242\234\350\211\262", nullptr));
        groupBox->setTitle(QCoreApplication::translate("MainWindow", "\350\242\253\350\243\201\345\211\252\345\244\232\350\276\271\345\275\242\345\217\202\346\225\260", nullptr));
        label->setText(QCoreApplication::translate("MainWindow", "\351\241\266\347\202\271\344\270\252\346\225\260\357\274\232", nullptr));
        lineEdit_n->setText(QCoreApplication::translate("MainWindow", "4", nullptr));
        groupBox_nodeList_2->setTitle(QCoreApplication::translate("MainWindow", "\345\244\232\350\276\271\345\275\242\351\241\266\347\202\271\345\235\220\346\240\207", nullptr));
        lineEdit_x0->setText(QCoreApplication::translate("MainWindow", "100", nullptr));
        label_x0_2->setText(QCoreApplication::translate("MainWindow", "x0\357\274\232", nullptr));
        label_y0->setText(QCoreApplication::translate("MainWindow", "y0\357\274\232", nullptr));
        lineEdit_y0->setText(QCoreApplication::translate("MainWindow", "100", nullptr));
        label_x1_5->setText(QCoreApplication::translate("MainWindow", "y1\357\274\232", nullptr));
        lineEdit_y1->setText(QCoreApplication::translate("MainWindow", "200", nullptr));
        label_x1_2->setText(QCoreApplication::translate("MainWindow", "x1\357\274\232", nullptr));
        lineEdit_x1->setText(QCoreApplication::translate("MainWindow", "300", nullptr));
        label_x1_7->setText(QCoreApplication::translate("MainWindow", "y2\357\274\232", nullptr));
        lineEdit_y2->setText(QCoreApplication::translate("MainWindow", "300", nullptr));
        label_x1_9->setText(QCoreApplication::translate("MainWindow", "x2\357\274\232", nullptr));
        lineEdit_x2->setText(QCoreApplication::translate("MainWindow", "100", nullptr));
        label_x1_11->setText(QCoreApplication::translate("MainWindow", "y3\357\274\232", nullptr));
        lineEdit_y3->setText(QCoreApplication::translate("MainWindow", "200", nullptr));
        label_x1_12->setText(QCoreApplication::translate("MainWindow", "x3\357\274\232", nullptr));
        lineEdit_x3->setText(QCoreApplication::translate("MainWindow", "200", nullptr));
        label_x1_13->setText(QCoreApplication::translate("MainWindow", "y4\357\274\232", nullptr));
        lineEdit_y4->setText(QCoreApplication::translate("MainWindow", "150", nullptr));
        label_x1_14->setText(QCoreApplication::translate("MainWindow", "x4\357\274\232", nullptr));
        lineEdit_x4->setText(QCoreApplication::translate("MainWindow", "210", nullptr));
        label_x1_15->setText(QCoreApplication::translate("MainWindow", "y5\357\274\232", nullptr));
        lineEdit_y5->setText(QCoreApplication::translate("MainWindow", "210", nullptr));
        label_x1_16->setText(QCoreApplication::translate("MainWindow", "x5\357\274\232", nullptr));
        lineEdit_x5->setText(QCoreApplication::translate("MainWindow", "400", nullptr));
        label_x1_17->setText(QCoreApplication::translate("MainWindow", "y6\357\274\232", nullptr));
        lineEdit_y6->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        label_x1_18->setText(QCoreApplication::translate("MainWindow", "x6\357\274\232", nullptr));
        lineEdit_x6->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        label_x1_19->setText(QCoreApplication::translate("MainWindow", "y7\357\274\232", nullptr));
        lineEdit_y7->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        label_x1_20->setText(QCoreApplication::translate("MainWindow", "x7\357\274\232", nullptr));
        lineEdit_x7->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        groupBox_2->setTitle(QCoreApplication::translate("MainWindow", "\350\243\201\345\211\252\347\252\227\345\217\243\345\217\202\346\225\260", nullptr));
        label_4->setText(QCoreApplication::translate("MainWindow", "\351\241\266\347\202\271\344\270\252\346\225\260\357\274\232", nullptr));
        lineEdit_n_c->setText(QCoreApplication::translate("MainWindow", "5", nullptr));
        groupBox_nodeList_5->setTitle(QCoreApplication::translate("MainWindow", "\345\244\232\350\276\271\345\275\242\351\241\266\347\202\271\345\235\220\346\240\207", nullptr));
        lineEdit_x0_c->setText(QCoreApplication::translate("MainWindow", "100", nullptr));
        label_x0_5->setText(QCoreApplication::translate("MainWindow", "x0\357\274\232", nullptr));
        label_y0_4->setText(QCoreApplication::translate("MainWindow", "y0\357\274\232", nullptr));
        lineEdit_y0_c->setText(QCoreApplication::translate("MainWindow", "150", nullptr));
        label_x1_44->setText(QCoreApplication::translate("MainWindow", "y1\357\274\232", nullptr));
        lineEdit_y1_c->setText(QCoreApplication::translate("MainWindow", "150", nullptr));
        label_x1_45->setText(QCoreApplication::translate("MainWindow", "x1\357\274\232", nullptr));
        lineEdit_x1_c->setText(QCoreApplication::translate("MainWindow", "250", nullptr));
        label_x1_46->setText(QCoreApplication::translate("MainWindow", "y2\357\274\232", nullptr));
        lineEdit_y2_c->setText(QCoreApplication::translate("MainWindow", "250", nullptr));
        label_x1_47->setText(QCoreApplication::translate("MainWindow", "x2\357\274\232", nullptr));
        lineEdit_x2_c->setText(QCoreApplication::translate("MainWindow", "250", nullptr));
        label_x1_48->setText(QCoreApplication::translate("MainWindow", "y3\357\274\232", nullptr));
        lineEdit_y3_c->setText(QCoreApplication::translate("MainWindow", "250", nullptr));
        label_x1_49->setText(QCoreApplication::translate("MainWindow", "x3\357\274\232", nullptr));
        lineEdit_x3_c->setText(QCoreApplication::translate("MainWindow", "100", nullptr));
        label_x1_50->setText(QCoreApplication::translate("MainWindow", "y4\357\274\232", nullptr));
        lineEdit_y4_c->setText(QCoreApplication::translate("MainWindow", "200", nullptr));
        label_x1_51->setText(QCoreApplication::translate("MainWindow", "x4\357\274\232", nullptr));
        lineEdit_x4_c->setText(QCoreApplication::translate("MainWindow", "220", nullptr));
        label_x1_52->setText(QCoreApplication::translate("MainWindow", "y5\357\274\232", nullptr));
        lineEdit_y5_c->setText(QCoreApplication::translate("MainWindow", "210", nullptr));
        label_x1_53->setText(QCoreApplication::translate("MainWindow", "x5\357\274\232", nullptr));
        lineEdit_x5_c->setText(QCoreApplication::translate("MainWindow", "400", nullptr));
        label_x1_54->setText(QCoreApplication::translate("MainWindow", "y6\357\274\232", nullptr));
        lineEdit_y6_c->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        label_x1_55->setText(QCoreApplication::translate("MainWindow", "x6\357\274\232", nullptr));
        lineEdit_x6_c->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        label_x1_56->setText(QCoreApplication::translate("MainWindow", "y7\357\274\232", nullptr));
        lineEdit_y7_c->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        label_x1_57->setText(QCoreApplication::translate("MainWindow", "x7\357\274\232", nullptr));
        lineEdit_x7_c->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
